server:
  port: 8080
spring:
  datasource:
    password: Lukky@2015
    url: jdbc:mysql://localhost:3306/employeeportal
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host:  smtp.gmail.com 
    port:  587
    username: a.ramakanth.recruiter.recruiter@gmail.com
    password:  esoi mvto spjk uzqd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        
   
  